### ISSUE TITLE
java.lang.RuntimeException: startPreview failed

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#11] opened 2018-02-22 09:40 UTC
Fatal Exception: java.lang.RuntimeException: startPreview failed
       at android.hardware.Camera.startPreview(Camera.java)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSource.a(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSource.start(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startWithException(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.start(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$7.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by shaubert** [comment] 2018-02-22 14:46
Devices
Xiaomi 34%
samsung 33%
Hexabyte 22%
HUAWEI 11%

Mi 4c 100%

Galaxy S6 Edge+ 67%
Galaxy S5 Mini 33%

Operating Systems
7 56%
4 22%
5 11%
6 11%

**Comment by sergiomarquesmoura** [comment] 2018-03-02 16:38
Hey @shaubert . From what I understood, you're currently using our `2.3.0` version. A newer `2.4.0` version was released last week, it might be worth to upgrade and check if the issues persist or not.

**Comment by shaubert** [comment] 2018-03-02 17:08
I think such response is possible for open source library, but not for proprietary paid solution. There are stacktraces in issues. You can at least check your code and add crash handling logic where you are unaware of what is happening. Or confirm that the issue is fixed in new version.

**Comment by rfreitas** [comment] 2018-03-02 19:13
I @shaubert , we can understand the concern and how your hands are tied to solve the problem. I guess @sergiomarquesmoura point is that we haven't been able to reproduce the problem, however we will look into this issue. The nature of the crash also needs to be understood to create proper handling logic, because we need to know what we can tell the user (try again, close other apps using the camera, etc.).
Do you have a percentage of users affected by the various crashes? so that we can prioritise the work on the crashes you have experienced?

**Comment by shaubert** [comment] 2018-03-07 15:05
I can not say the percentage but around 300 users are affected in total by all issues. These ones are in top of our crashlytics report.

**Comment by seewah** [comment] 2018-04-05 17:17
Fixed in version `3.0.0`. See [changelog](https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD#300---2018-04-05)

**Closed by seewah** 2018-04-05 17:17 UTC

**Comment by Eselfar** [comment] 2018-04-06 11:27
@seewah I'm not using this library but I'm currently facing the same issue in my own app, and it's difficult to figure out what is the problem as the error message is only: `startPreview failed`. 
It happened to me after I installed an app from the store together with ARCore. Since then all the apps installed on the phone display errors when accessing the camera.

So I was wondering if it's possible to detail what was the problem and how you managed to fix it as it could help other people too.
