### ISSUE TITLE
Google Play Store Violation: Deadline August 30, 2022

### ISSUE THREAD

**Issue by mdesjardins** [onfido/onfido-android-sdk#207] opened 2022-07-28 18:07 UTC
#### What was the expected behaviour?
We do not receive a warning about analytics libraries when we submit our app containing Onfido to the app store.

#### What happened instead?
We received the following warning from the Google Play store:

> Jun 10, 2022 17:17
> Your app [redacted] version code [redacted] includes SDK com.segment.analytics.android:analytics or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy.
>
> Starting from August 30, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the User Data policy may be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code if available from your SDK provider, or removing this SDK from your app.
>
> According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information.
>
> ACTION REQUIRED: Upload a new compliant version AND deactivate the noncompliant version.
>
> Read through the User Data policy for more details, and how to submit an updated app for review here.
>
> If you've reviewed the policy and feel our decision may have been in error, please reach out to our policy support team.

We didn't think we were using the segment analytics library, so we ran `./gradlew :app:dependencies` on our project, thinking it was a transitive dependency. Strangely, we did not see the segment library listed in the output.

```
💎 🐍 v3.8.12  ❯ ./gradlew :app:dependencies > x.x
💎 🐍 v3.8.12  ❯ grep segment x.x
(no output)
```

On a whim, I downloaded several of our project dependencies' .aar files directly from Maven Central, one of which was onfido-capture-sdk-core-12.2.2. I unzipped the .aar file, and then listed the contents of the classes.jar file within it, and found the following:

```
🐍 v3.8.12  ~/Downloads/onfido-core-12.2.2 ❯ unzip -l classes.jar
.
.
(snipped)
.
.
      767  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$a.class
     1498  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$b.class
      868  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$c.class
      810  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$d$a.class
     2654  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$d.class
      808  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$e$a.class
      947  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$e.class
     1540  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$f.class
     1621  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$g.class
      688  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$h.class
     7204  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$i.class
     1315  01-01-1981 01:01   com/onfido/segment/analytics/Analytics$j.class
    17257  01-01-1981 01:01   com/onfido/segment/analytics/Analytics.class
     1124  01-01-1981 01:01   com/onfido/segment/analytics/AnalyticsActivityLifecycleCallbacks$a$a.class
      885  01-01-1981 01:01   com/onfido/segment/analytics/AnalyticsActivityLifecycleCallbacks$a.class
     2020  01-01-1981 01:01   com/onfido/segment/analytics/AnalyticsActivityLifecycleCallbacks$b.class
     5881  01-01-1981 01:01   com/onfido/segment/analytics/AnalyticsActivityLifecycleCallbacks.class
      817  01-01-1981 01:01   com/onfido/segment/analytics/Properties.class
     1135  01-01-1981 01:01   com/onfido/segment/analytics/a$a.class
     7071  01-01-1981 01:01   com/onfido/segment/analytics/a.class
      887  01-01-1981 01:01   com/onfido/segment/analytics/b$a.class
      612  01-01-1981 01:01   com/onfido/segment/analytics/b$b.class
     5728  01-01-1981 01:01   com/onfido/segment/analytics/b.class
     1696  01-01-1981 01:01   com/onfido/segment/analytics/c$a.class
      694  01-01-1981 01:01   com/onfido/segment/analytics/c$b.class
      864  01-01-1981 01:01   com/onfido/segment/analytics/c$c.class
      889  01-01-1981 01:01   com/onfido/segment/analytics/c$d.class
     2290  01-01-1981 01:01   com/onfido/segment/analytics/c.class
     2163  01-01-1981 01:01   com/onfido/segment/analytics/d.class
     4108  01-01-1981 01:01   com/onfido/segment/analytics/e.class
      830  01-01-1981 01:01   com/onfido/segment/analytics/f$a.class
     1516  01-01-1981 01:01   com/onfido/segment/analytics/f$b.class
     4253  01-01-1981 01:01   com/onfido/segment/analytics/f.class
      794  01-01-1981 01:01   com/onfido/segment/analytics/g$a.class
      870  01-01-1981 01:01   com/onfido/segment/analytics/g$b.class
      991  01-01-1981 01:01   com/onfido/segment/analytics/g$c.class
      947  01-01-1981 01:01   com/onfido/segment/analytics/g$d.class
      943  01-01-1981 01:01   com/onfido/segment/analytics/g$e.class
      946  01-01-1981 01:01   com/onfido/segment/analytics/g$f.class
      947  01-01-1981 01:01   com/onfido/segment/analytics/g$g.class
     1047  01-01-1981 01:01   com/onfido/segment/analytics/g$h.class
      945  01-01-1981 01:01   com/onfido/segment/analytics/g$i.class
     2382  01-01-1981 01:01   com/onfido/segment/analytics/g$j$a.class
     1457  01-01-1981 01:01   com/onfido/segment/analytics/g$j.class
      790  01-01-1981 01:01   com/onfido/segment/analytics/g$k.class
     5632  01-01-1981 01:01   com/onfido/segment/analytics/g.class
      339  01-01-1981 01:01   com/onfido/segment/analytics/h$a.class
      343  01-01-1981 01:01   com/onfido/segment/analytics/h$b.class
      397  01-01-1981 01:01   com/onfido/segment/analytics/h.class
     1405  01-01-1981 01:01   com/onfido/segment/analytics/i.class
      335  01-01-1981 01:01   com/onfido/segment/analytics/j$a.class
     1099  01-01-1981 01:01   com/onfido/segment/analytics/j$b.class
     1019  01-01-1981 01:01   com/onfido/segment/analytics/j$c.class
      580  01-01-1981 01:01   com/onfido/segment/analytics/j.class
     1227  01-01-1981 01:01   com/onfido/segment/analytics/k$a.class
     1375  01-01-1981 01:01   com/onfido/segment/analytics/k.class
      991  01-01-1981 01:01   com/onfido/segment/analytics/l$a.class
      938  01-01-1981 01:01   com/onfido/segment/analytics/l$b.class
     1085  01-01-1981 01:01   com/onfido/segment/analytics/l$c.class
     7018  01-01-1981 01:01   com/onfido/segment/analytics/l.class
     1769  01-01-1981 01:01   com/onfido/segment/analytics/m$a.class
      852  01-01-1981 01:01   com/onfido/segment/analytics/m$b.class
      704  01-01-1981 01:01   com/onfido/segment/analytics/m$c.class
     1620  01-01-1981 01:01   com/onfido/segment/analytics/m$d.class
     1243  01-01-1981 01:01   com/onfido/segment/analytics/m$e.class
     1160  01-01-1981 01:01   com/onfido/segment/analytics/m$f.class
    10096  01-01-1981 01:01   com/onfido/segment/analytics/m.class
     1182  01-01-1981 01:01   com/onfido/segment/analytics/n$a.class
     1955  01-01-1981 01:01   com/onfido/segment/analytics/n.class
     1302  01-01-1981 01:01   com/onfido/segment/analytics/o$a.class
     1459  01-01-1981 01:01   com/onfido/segment/analytics/o.class
     2286  01-01-1981 01:01   com/onfido/segment/analytics/p$a.class
     5128  01-01-1981 01:01   com/onfido/segment/analytics/p.class
```

So it *appears* that Onfido is directly embedding some form of the segment analytics library within their .aar file, rather than declaring it as an external dependency? And because of that, Google is detecting this and issuing a warning?

We need to have this rectified ASAP so that we don't risk losing the ability to release our app. 

#### Version info:

- `onfido-capture-sdk` version: 12.2.2
- Android API version(s):

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 24
- Support library version (if applicable):

#### Steps to reproduce:

See above.

#### Onfido Flow initialization code:

n/a

#### Issue severity information (number of users/crashes if applicable):

Potential loss of ability to our release app (high severity).

**Comment by gurpreet-onfido** [comment] 2022-07-29 04:50
Hello Mike,

Greetings for the day!
 
I have confirmed with the team that this issue was caused by the usage of Android_ID (in our codebase as well as Segment SDK) and is fixed in our latest release 12.2.2(https://github.com/onfido/onfido-android-sdk/releases/tag/12.2.2). 

If you have already upgraded to the latest release, you are good to go.
 
I hope this helps!
 
Please let us know if there is anything else I can help you with.
 
Kind regards,
Gurpreet Singh

**Comment by mdesjardins** [comment] 2022-07-29 11:50
Ahh, gotcha. It turns out our team was using 12.2.0, not 12.2.2. I saw the use of segment was still in 12.2.2 and jumped to conclusions, my bad. We'll try 12.2.2 and see what happens!

**Comment by sunil-differenz** [comment] 2022-12-16 05:08
Hi @gurpreet-onfido 

Our App was rejected by the google play store.

This is what we got

**Your app is using the Onfido SDK which collects but may not be limited to IMSI and Advertising ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.

You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.

If necessary, you can consult your SDK provider(s) for further information.**

**Comment by gurpreet-onfido** [comment] 2022-12-30 08:26
Hello @sunil-differenz 

Could you please let us know the version of the SDK you are using?

Kind regards
Gurpreet Singh

**Closed** 2023-03-10 12:44 UTC
