### ISSUE TITLE
Error on Submit video

### ISSUE THREAD

**Issue by pouriabagheri** [onfido/onfido-android-sdk#122] opened 2020-05-12 01:51 UTC
#### Version info: 

- `onfido-capture-sdk` version: com.onfido.sdk.capture:onfido-capture-sdk:5.3.3
- Android API version(s): 23

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 17
- Support library version (if applicable):

#### Onfido Flow initialization code: 
```
OnfidoConfig.Builder onfidoConfigBuilder = OnfidoConfig.builder(getContext()).withToken(token).withApplicant(applicantId);
FlowStep[] flowStepsWithOptions = new FlowStep[]{};
flowStepsWithOptions = new FlowStep[]{
                                    new CaptureScreenStep(DocumentType.PASSPORT, CountryCode.valueOf(onfidoCountryCode)),
                                    new FaceCaptureStep(FaceCaptureVariant.VIDEO)
                            };
 onfidoConfigBuilder.withCustomFlow(flowStepsWithOptions);
 OnfidoConfig onfidoConfig = onfidoConfigBuilder.build();
```
#### Other useful info:
![97203456_236719827431369_2286281898491641856_n](https://user-images.githubusercontent.com/5735478/81629539-f4d50480-9435-11ea-800b-b33667a5f01f.jpg)

**Comment by gokhanaliccii** [comment] 2020-05-13 15:42
@pouriabagheri we've recently fixed the problem but we haven't published yet, I'll ping you when we release a new version.

**Comment by pouriabagheri** [comment] 2020-05-14 01:38
@gokhanaliccii 

1. Did you blur out the person in the screenshot or it is the actual view?
blurred out the screenshot.
2. What is the device model? OPPO CPH1607 (API 23)
3. Are you able to reproduce the issue on different devices? first time report via user
4. Are you able to reproduce the issue on the latest version of the SDK? the issue was raised by our user and we haven't updated our onfido SDK on production. 

May i know 
- does sdk 6.0.0 work with  onfido API 2.0 or 3.0  or both?
- is this a known issue? is it resolved in sdk 6.0.0 ?

**Comment by gokhanaliccii** [comment] 2020-05-14 09:41
does sdk 6.0.0 work with onfido API 2.0 or 3.0 or both?
SDK(6.0.0) uses Onfido API 3.0 

is this a known issue? is it resolved in sdk 6.0.0 ?
It's not known issue

**Comment by makarov-nsk** [comment] 2020-11-16 09:23
The issue is still opened? In which sdk version is the fix planned?

**Comment by gokhanaliccii** [comment] 2021-07-14 16:37
Recently we have released a new [SDK version](https://github.com/onfido/onfido-android-sdk/releases/tag/10.0.0) which contains lots of improvements

Would you mind testing the [latest version](https://github.com/onfido/onfido-android-sdk/releases/tag/10.0.0)?

**Comment by musagil** [comment] 2021-09-09 11:26
Hi @pouriabagheri ,

Can you please confirm that the issue has been fixed?

**Comment by jdeebee** [comment] 2022-05-12 12:01
Closing as the mentioned SDK version is outdated and there has been no new update on this issue from the customer. Please update to the latest SDK version (12.0.0) which includes several fixes and improvements.

**Closed by jdeebee** 2022-05-12 12:01 UTC
