### ISSUE TITLE
Onfido crashes if jetifier is disabled

### ISSUE THREAD

**Issue by bracadabra** [onfido/onfido-android-sdk#143] opened 2020-12-09 14:57 UTC
#### What was the expected behaviour?
Onfido is moved to AndroidX and works as expected

#### What happened instead?
Onfido crashes

#### Version info:

- `onfido-capture-sdk` version: 7.3.0
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21

#### Additional LogCat output:

```
2020-12-09 13:39:16.921 32713-32713/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.revolut.revolut.test, PID: 32713
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/ConfigurationCompat;
        at com.google.android.gms.internal.firebase_ml.zznv.zzlm(Unknown Source:70)
        at com.google.android.gms.internal.firebase_ml.zznv.zza(Unknown Source:50)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.<init>(Unknown Source:21)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.zza(Unknown Source:13)
        at com.google.firebase.ml.vision.FirebaseVision.getVisionFaceDetector(Unknown Source:15)
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.getFaceDetector(Unknown Source:8)
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.access$getFaceDetector(Unknown Source:0)
        at com.onfido.android.sdk.capture.detector.face.FaceDetector$fastDetector$2.invoke(Unknown Source:6)
        at com.onfido.android.sdk.capture.detector.face.FaceDetector$fastDetector$2.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.getFastDetector(Unknown Source:7)
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.close(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stopFaceTracking(Unknown Source:9)
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stop(Unknown Source:40)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture(Unknown Source:35)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$capture(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$setupCaptureButton$1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.os.ConfigurationCompat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.revolut.revolut.test-8wu_aa_T4Q9jypU9Sg1wuw==/base.apk"],nativeLibraryDirectories=[/data/app/com.revolut.revolut.test-8wu_aa_T4Q9jypU9Sg1wuw==/lib/arm64, /data/app/com.revolut.revolut.test-8wu_aa_T4Q9jypU9Sg1wuw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.internal.firebase_ml.zznv.zzlm(Unknown Source:70) 
        at com.google.android.gms.internal.firebase_ml.zznv.zza(Unknown Source:50) 
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.<init>(Unknown Source:21) 
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.zza(Unknown Source:13) 
        at com.google.firebase.ml.vision.FirebaseVision.getVisionFaceDetector(Unknown Source:15) 
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.getFaceDetector(Unknown Source:8) 
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.access$getFaceDetector(Unknown Source:0) 
        at com.onfido.android.sdk.capture.detector.face.FaceDetector$fastDetector$2.invoke(Unknown Source:6) 
        at com.onfido.android.sdk.capture.detector.face.FaceDetector$fastDetector$2.invoke(Unknown Source:0) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.getFastDetector(Unknown Source:7) 
        at com.onfido.android.sdk.capture.detector.face.FaceDetector.close(Unknown Source:0) 
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stopFaceTracking(Unknown Source:9) 
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stop(Unknown Source:40) 
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture(Unknown Source:35) 
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$capture(Unknown Source:0) 
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$setupCaptureButton$1.onClick(Unknown Source:2) 
        at android.view.View.performClick(View.java:6669) 
        at android.view.View.performClickInternal(View.java:6638) 
        at android.view.View.access$3100(View.java:789) 
        at android.view.View$PerformClick.run(View.java:26145) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-12-09 13:41:54.528 1860-1860/com.revolut.revolut.test E/AndroidRuntime: FATAL EXCEPTION: main
```

**Comment by NoNews** [comment] 2020-12-09 15:54
We have such dependencies related to ml: 
`com.google.mlkit:barcode-scanning:16.0.3`
`com.google.mlkit:face-detection:16.0.2`

But inside `Onfido` you probably have:
`com.google.firebase:firebase-ml-vision, 
`com.google.firebase:firebase-ml-vision-face-model`

Could it be the reason?

**Comment by androideveloper** [comment] 2020-12-11 10:37
The same crash here after disablign Jetifier. Onfido has dependency on Firebase-ml-vision, yes.
![Screenshot 2020-12-11 at 11 36 41](https://user-images.githubusercontent.com/1249919/101893539-2c12bc00-3ba5-11eb-925c-7468498f973d.png)
Onfido version 7.1.0

**Comment by burakeregar** [comment] 2020-12-14 17:08
Could you please share which versions of the dependencies below you are using?
```
classpath 'com.google.gms:google-services:x.y.z'
classpath 'com.android.tools.build:gradle:x.y.z'
```

Are you able to reproduce the issue on the [sample app](https://github.com/onfido/onfido-android-sdk/tree/master/sample-app)? I have tried by disabling jetifier but couldn't reproduce it. 

Gradle doesn't allow me (build fails) to add ML Kit libraries you mentioned on top of the Onfido SDK as both of them contain the same `.so` file which is `libbarhopper_v2.so` so I am unable to test that case. 

Do you mind sharing steps to reproduce the issue on the sample app? If you are also not able to reproduce it on the sample app, we will need to deep dive into the dependency related scenarios.

**Comment by bracadabra** [comment] 2020-12-14 18:06
Hi @burakeregar, thank you for help. We use:

```
classpath 'com.google.gms:google-services:4.3.4'
classpath 'com.android.tools.build:gradle:4.0.1'
```

And we declare onfido dependency like this:
implementation 'com.onfido.sdk.capture:onfido-capture-sdk:7.3.0' {
    exclude group: 'com.android.support'
    exclude group: 'com.google.firebase', module: "firebase-ml-vision-barcode-model"
}
implementation 'com.onfido.sdk.capture:onfido-capture-sdk-core:7.3.0' {
    exclude group: 'com.google.firebase', module: "firebase-ml-vision-barcode-model"
}

I will try to reproduce it on the sample app later.

**Comment by burakeregar** [comment] 2020-12-14 18:16
Thanks for the information @bracadabra,

Perhaps not related to this issue but it's worth checking. Are you using core and the full SDK implementation for different variants/flavours? If not, you don't need the core dependency as it's already included in the full (`com.onfido.sdk.capture:onfido-capture-sdk`) SDK. If that's the case, it might be worth removing the core SDK implementation.

**Comment by androideveloper** [comment] 2020-12-14 18:46
Hi @burakeregar . Thanks for checking!
Our setup
```
classpath 'com.google.gms:google-services:4.3.4'
classpath 'com.android.tools.build:gradle:3.6.3' (can't update to 4.0 because of other issues)

...
    api(onfido) { // 7.1.0
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-basement'
    }
```

**Comment by androideveloper** [comment] 2020-12-15 08:41
I tried to remove the `exclude group` part, still crashing

**Comment by burakeregar** [comment] 2020-12-30 18:24
I presume this issue is due to Firebase ML Vision using old support library for `ConfigurationCompat`. We will be migrating our `firebase-ml-vision` dependencies to Google ML Kit as recommended [here](https://developers.google.com/ml-kit/migration). I will update here once that work is released. In the meantime, please let us know if you can reproduce the issue on the sample app?

**Comment by androideveloper** [comment] 2020-12-31 08:44
Thanks for the update. Updating Firebase should resolve the issue 👍

**Comment by lassem** [comment] 2021-01-20 13:15
Fwiw, latest AGP, version 4.1.2 complains about this:
```
WARNING: [Processor] Library '/Users/lasse/.gradle/caches/modules-2/files-2.1/com.onfido.sdk.capture/onfido-capture-sdk-core/8.0.0/613a8149659c24cb9422df6f2ba8ed11698967e2/onfido-capture-sdk-core-8.0.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/appcompat/widget/AppCompatImageView'
 Example of support library reference: 'android/support/annotation/Nullable'
```

**Comment by NoNews** [comment] 2021-01-20 15:37
How soon are you going to release new version with ml migration?

**Comment by burakeregar** [comment] 2021-01-20 15:58
The migration will be included in the next release. I don't have an exact date for the release but we will be aiming to ship it as soon as possible.

**Comment by burakeregar** [comment] 2021-02-03 15:08
We have now migrated from Firebase ML to Google ML Kit as well as disabling `jetifier` on our side. [Onfido Android SDK 8.1.0](https://github.com/onfido/onfido-android-sdk/releases/tag/8.1.0).

**Closed by burakeregar** 2021-02-03 15:08 UTC

**Comment by androideveloper** [comment] 2021-05-26 14:38
We have updated to the latest version of onfido, but still getting warnings from AGP plugin.
Similar ticket https://github.com/onfido/onfido-android-sdk/issues/158
Is it fine to disable Jetifier at this point?

**Comment by R4md4c** [comment] 2021-11-01 10:17
Hey @androideveloper please check my comment on the referenced ticket 
https://github.com/onfido/onfido-android-sdk/issues/158#issuecomment-956105673
