### ISSUE TITLE
IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by androidexperts155** [onfido/onfido-android-sdk#101] opened 2020-02-26 04:21 UTC
#### Version info:

- `onfido-capture-sdk` version:
- Android API version(s):

- `compileSdkVersion`:
- `targetSdkVersion`:
- `minSdkVersion`:
- Support library version (if applicable):

#### Other useful info:
_screenshots, videos, etc._

**Comment by gurpreetburmi** [comment] 2020-02-26 04:57
Hello @androidexperts155 Could you please share the complete error message. 

Also, if you could provide us more information(sdk-version, flow initialization code ) to reproduce the error that would be great. 

Looking forward to your response.

**Comment by androidexperts155** [comment] 2020-02-29 06:59
Thanks for Your response, I am getting one more issue actually i am getting response success after post the document and  other information but the data is not uploaded to the server, even i use the same SDK token in IOS app it is working fine but issue are in Aadroid App

**Comment by gurpreetburmi** [comment] 2020-03-02 03:52
Hello @androidexperts155 My colleague has already answered this for you in your product support ticket with us. Could you please confirm us if that resolved the issue for you?

**Comment by androidexperts155** [comment] 2020-03-02 05:46
@gurpreetburmi I did not get solution yet, the posted issue is resolved but again I'm getting other issue, i am getting the success from onfido but data is not uploaded

**Comment by gurpreetburmi** [comment] 2020-03-02 10:23
Hello there!

Let me share the update here for your reference. 

As the SDK is only responsible for capturing and uploading photos/videos, you would need to start a check on your backend server using the [Onfido API](https://documentation.onfido.com/#create-check).

You will need to create an express check by making a request to [create a check endpoint](https://documentation.onfido.com/#create-check), using the applicant id. If you are just verifying a document, you only have to include a [document report](https://documentation.onfido.com/#document-report) as part of the check. On the other hand, if you are verifying a document and a face photo/live video, you will also have to include a [facial similarity report](https://documentation.onfido.com/#facial-similarity-report) with the corresponding variants: standard for the photo option and video for the video option.

```
$ curl https://api.onfido.com/v2/applicants/YOUR_APPLICANT_ID/checks \
    -H 'Authorization: Token token=YOUR_API_TOKEN' \
    -d 'type=express' \
    -d 'reports[][name]=document' \
    -d 'reports[][name]=facial_similarity' \
    -d 'reports[][variant]=standard'
```

You mentioned in your previous response that you are able to create a check after the flow is completed in iOS SDK, but not in the Android SDK, could you please let me know how are you creating a check after the flow is completed in the iOS SDK? 

In Android, you could make use of callbacks when there is successful completion of the flow, i.e. the document and photo/video were uploaded to onfido. 
To receive the result from the flow, you should override the method onActivityResult. Typically, on success, you would [create a check](https://github.com/onfido/onfido-android-sdk#creating-checks) on your backend server.

```
@Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    ...
    onfido.handleActivityResult(resultCode, data, new Onfido.OnfidoResultListener() {
        @Override public void userCompleted(Captures captures) {
            //communicate with your backend and initiate the check
        }
        @Override public void userExited(ExitCode exitCode) {
            //User left the sdk flow without completing it
        }
        @Override public void onError(OnfidoException exception) {
            // An exception occurred during the flow
        }
    });
}
```
When the user has successfully completed the flow, and the captured photos/videos have been uploaded, the userCompleted method will be invoked. The Captures object contains information about the document and face captures made during the flow. With the applicant id, you can then [create a check ](https://github.com/onfido/onfido-android-sdk#creating-checks)for the user via your backend. On the other hand, if the user exits the flow without completing it, the userExited method will be invoked. Note that some images may have already been uploaded by this stage.

Sample of a Captures instance returned by a flow with FlowStep.CAPTURE_DOCUMENT and FlowStep.CAPTURE_FACE:

```
Document: 
        Front: DocumentSide(id=document_id, side=FRONT, type=DRIVING_LICENCE)
        Back: DocumentSide(id=document_id, side=BACK, type=DRIVING_LICENCE)
        Type: DRIVING_LICENCE
Face:
    Face(id=face_id, variant=PHOTO)
```

I hope this helps and I look forward to hearing from you soon.

**Comment by gokhanaliccii** [comment] 2020-06-03 17:05
@androidexperts155 Can you please confirm that the issue has resolved?

**Comment by burakeregar** [comment] 2020-06-29 16:42
Closing due to inactivity. Please reopen if the issue still exists.

**Closed by burakeregar** 2020-06-29 16:42 UTC
Labels: needs info
