### ISSUE TITLE
Localization issue using withLocale() function

### ISSUE THREAD

**Issue by dave-mls** [onfido/onfido-android-sdk#134] opened 2020-10-12 15:32 UTC
Hi there,
I found an issue customizing the sdk locale.

#### What was the expected behaviour?

The locale is forced to the selected one every time the sdk is initialized.

#### What happened instead?

It is applied only the first time.
If I go back and then re-initialize the sdk, the selected locale is ignored.

#### Version info:

- `onfido-capture-sdk` version: 7.3.0

#### Steps to reproduce:

- Set the device locale to Italian (or one of the other not natively supported locales);
- Add the strings.xml in the right values dir within the project;
- Customize the locale using the OnfidoConfig.builder.withLocale(Locale.ENGLISH);
- Start the activity for result through a button.onClickListener;
- The strings are localized with the right forced locale;
- Go back, canceling the flow;
- Click again in the button to re-start the activity;
- Now the strings are localized using the device locale, ignoring the forced english one.

#### Onfido Flow initialization code:

```
OnfidoClient.startActivityForResult(fragment, 12345, OnfidoConfig.builder(fragment.requireContext()).apply {
    withSDKToken(token, ExpirationHandler(mCacheDir, apiToken, applicationId, applicantId))
    withLocale(if (user.platform == Platform.IT) Locale.ITALIAN else Locale.ENGLISH)
//    Tested also with the following, with the same result
//    withLocale(Locale.ENGLISH)
}.build())
```

#### Other useful info:

![ezgif-3-793e2fa10f03](https://user-images.githubusercontent.com/72750738/95764213-6d274680-0cb0-11eb-8f89-fe742bd4b2fc.gif)

**Comment by gokhanaliccii** [comment] 2020-10-12 16:35
@dave-mls  sorry for the inconvenience, 

can you please share the android version of your device?

**Comment by dave-mls** [comment] 2020-10-12 16:48
Sorry I was sure to have added it on the feedback..
Android 10, API version 29.

**Comment by burakeregar** [comment] 2020-10-19 17:10
Hi @dave-mls,

Thank you for providing details. Unfortunately, I am currently unable to reproduce the issue on my end with an Android 10 device.

- Could you try to reproduce this with our sample app to eliminate any potential integration issues?
- Is this a device/OS specific issue or are you also able to reproduce this on different devices with a different OS?

**Comment by dave-mls** [comment] 2020-10-20 11:21
Hi @burakeregar, 
it was a bit tricky, but I found a way to reproduce it on real devices and emulators with Android API level 28, 29 and 30, with both `7.2.0` and `7.3.0` `onfido-capture-sdk` versions, using your sample app, with a few changes.

**Steps to reproduce the issue with the sample app:**
- Clone the project from the repo
- Edit the `build.gradle` file (the _app module_ one) to use the latest `appcompat` library:
   - `implementation 'androidx.appcompat:appcompat:1.2.0'`
- Edit the `OnfidoConfig.builder` in the `MainActivity` to force the locale to `EN`:
   - `.withLocale(Locale.ENGLISH)`
- Create the `values-it` directory under the `res` one
- Paste the `strings.xml` file (the complete one linked in the documentation) into the `values-it` dir
- Edit the string resources inside it to match the following ones:
   - `<string name="onfido_locale">it</string>`
   - `<string name="onfido_welcome_view_toolbar_title">Verifica identità</string>`
   - `<string name="onfido_welcome_view_title">Verifica la tua identità</string>`
   - `<string name="onfido_welcome_view_time">Ci vorranno meno di 2 minuti</string>`
   - `<string name="onfido_welcome_view_document_capture_title">Fai una foto del documento di identità</string>`
   - `<string name="onfido_welcome_view_face_capture_title">Fatti un selfie</string>`
   - `<string name="onfido_welcome_view_liveness_capture_title">Fatti un video-selfie</string>`
- Set the device / emulator main language to `Italian`
- Now launch the sample app, tap on the `NEXT` button once to see the _Welcome step_ translated within the selected locale, tap on `back`, tap on `NEXT` button once again to see the _Welcome step_ translated within the device locale.
- From now on, the SDK will be translated within the device locale, until the app is killed from background and the steps can be re-iterated.

**Comment by burakeregar** [comment] 2020-10-21 17:24
Really appreciate this @dave-mls, I am able to reproduce the issue now. It seems like this happens due to a major change on [appcompat:1.2.0](https://developer.android.com/jetpack/androidx/releases/appcompat#1.2.0). I have created an internal ticket to make it working with `appcompat 1.2.0`. I will update here once it's released. If you don't prefer to wait until our fix, you can switch to `appcompat:1.1.0` temporarily.

**Comment by slacabos** [comment] 2021-02-01 11:48
Hello @burakeregar, do you have any updates on this issue?

Thank you

**Comment by burakeregar** [comment] 2021-02-01 11:50
Hi @slacabos,

We have fixed the issue and it will be included in the next release which we are aiming to ship this week.

**Comment by dave-mls** [comment] 2021-02-01 12:10
Ciao @burakeregar 

This is a great news!
We just discovered this other issue, regarding a mixed localization in the same flow.
Will it be fixed by the same fix?
https://user-images.githubusercontent.com/72750738/106456782-4d4da580-648e-11eb-801c-fd34f43e142a.mp4

Thank you! ;)

**Comment by burakeregar** [comment] 2021-02-03 15:10
[Android SDK 8.1.0](https://github.com/onfido/onfido-android-sdk/releases/tag/8.1.0) which includes a fix for this issue has been released.

**Closed by burakeregar** 2021-02-03 15:10 UTC
Labels: bug
